name: UPilotFlow Sample

on:
  workflow_dispatch:

jobs:
  editmode-upilot_flow:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, node24

      - name: Run UPilotFlow
        shell: pwsh
        run: |
          $unity = "C:\Program Files\Unity\Hub\Editor\6000.6.0a2\Editor\Unity.exe"
          & $unity `
            -projectPath $PWD `
            -quit `
            -executeMethod CodingRiver.UPilot.Flow.UPilotFlowCliEntry.RunAllFromCommandLine `
            -upilotFlow.headed false `
            -upilotFlow.reportPath ./Reports `
            -upilotFlow.screenshotOnFailure true `
            -upilotFlow.testFilter *

      - name: Upload Reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1, node24
        with:
          name: upilot_flow-reports
          path: Reports
